plugins:
  microsoft_auth_enabled:
    client: true
    default: false
  microsoft_auth_client_id:
    client: false
    default: ''
  microsoft_auth_client_secret:
    client: false
    default: ''
  office365_tenant_id:
    client: false
    default: ''